name: Deployment Workflow
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing ssh connection
      uses: sahibzadafahad-whizpool/express-hello-world@master 
      with:
        host: 54.39.177.68
        username: express
        password: ${{ secrets.express }}
        port: 22
        script: |
          cd express-hello-world
          git pull origin master
          git status
