name: Deployment Workflow
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: self-hosted
    steps:
    - name: testing ssh connection
      uses: appleboy/ssh-action@master 
      with:
        host: 54.39.177.68
        username: express
        password: ${{ secrets.express }}
        port: 22
        script: |
          # script will go here
