name: deployement workflow
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: 54.39.177.68
        username: express
        key: ${{ secrets.express }}
        port: 22
        script: |
          cd express-hello-world
          git pull origin master
          git status
          npm install
