name: deployement workflow
on:
  push:
    branches: [ development ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: 54.39.177.68
        username: express
        key: ${{ secrets.express }}
        port: 22
        script: |
          cd express-hello-world
          git pull origin development
          git status
          npm install
          chmod 777 -R container.sh
          ./container.sh
          docker build -t express-hello-world .
          docker run --name hello-world -it -d -p 3000:3000 express-hello-world
